### ISSUE TITLE
Finish Scholarly technical report

### ISSUE THREAD

**Issue by afurculita** [wadoteam/scholarly#1]
We need to create a Scholarly HTML technical report (its digital content will be equivalent to a minimum of four A4 printed pages) consisting of preliminary considerations about the internal data structures/models to be used and the external data sources – e.g., public Web services and/or APIs – managed by the Web application to be developed.

http://www.kevinboone.net/howto_report.html

**Comment by afurculita** [comment]
@constantinserediuc va trebui sa continui cu ce s-a comis deja in master

**Comment by constantinserediuc** [comment]
https://wadoteam.github.io/scholarly/
